### ISSUE TITLE
F-Droid fails to build

### ISSUE THREAD

**Issue by licaon-kter** [niccokunzmann/coloring-book#114]
https://f-droid.org/wiki/index.php?title=eu.quelltext.coloring/lastbuild_4&oldid=280147

**Comment by niccokunzmann** [comment]
Thanks for reporting this!

**Comment by urbalazs** [comment]
Since the last version is built on F-Droid successfully, this issue can be closed.

**Comment by niccokunzmann** [comment]
Thanks!
